### ISSUE TITLE
Stopped working with gpt-3.5-turbo

### ISSUE THREAD

**Issue by carlosvaldesweb** [yethee/tiktoken-php#15]
I've been using the yethee/tiktoken package successfully until yesterday. However, starting today, it no longer works with the gpt-3.5-turbo model. I am receiving the following error:

```php
[2024-07-16 17:19:30] local.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/Vocab/Vocab.php:88)
[stacktrace]
#0 /Volumes/develop/parafrasist-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/Volumes/develo...', 88)
#1 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/Vocab/Vocab.php(88): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/Volumes/develo...', 88)
#2 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/Vocab/Vocab.php(65): Yethee\\Tiktoken\\Vocab\\Vocab::fromStream(Resource id #1060)
#3 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/Vocab/Loader/DefaultVocabLoader.php(38): Yethee\\Tiktoken\\Vocab\\Vocab::fromFile('/var/folders/gc...')
#4 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/EncoderProvider.php(180): Yethee\\Tiktoken\\Vocab\\Loader\\DefaultVocabLoader->load('https://openaip...')
#5 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/EncoderProvider.php(141): Yethee\\Tiktoken\\EncoderProvider->getVocab('cl100k_base')
#6 /Volumes/develop/parafrasist-backend/vendor/yethee/tiktoken/src/EncoderProvider.php(117): Yethee\\Tiktoken\\EncoderProvider->get('cl100k_base')
```

### Usage in my function
```php
public function getNumberTokensFromString(string $text): int
    {
        $provider = new EncoderProvider();
        $encoder = $provider->getForModel($this->model);
        $tokens = $encoder->encode(trim($text));

        return count($tokens);
    }
```

**Comment by yethee** [comment]
I think a data file for vocabulary is corrupted.

Try to clear the [cache](https://github.com/yethee/tiktoken-php?tab=readme-ov-file#cache). This should solve your issue.

**Comment by yethee** [comment]
You can update the package to the latest version `0.5.1`. The broken cache will be invalidated and data for vocab will be loaded again.
